### ISSUE TITLE
Abandoned

### ISSUE THREAD

**Issue by tolgaaaltas** [XEngine/flarum-ext-turkish#1]
Packagist.org üzerinden Abandoned olarak işaretlemeniz mümkün mü acaba? beta 6'dan itibaren desteklenmemiş ve kullanıcılar hala sizin paketinizi yüklemeye çalışarak eksik çeviri ile sistemi kullanmaya çalışıyorlar.

**Comment by XEngine** [comment]
@tolgaaaltas Teşekkür ederim, işaretlendi!
